### PR TITLE
Adding in travis-ci config

### PR DESCRIPTION
**Pull request by chrisosaurus**
As per #13 you will have to authorise travis via:

Please visit https://travis-ci.org/wolfgangj/bone-lisp
sign in with github
authorise it for your account
then on https://travis-ci.org/wolfgangj/bone-lisp
there should be a gray box next to bone-lisp, clicking it will turn it green
once green we are good to go and I can do the rest via PRs :)

To see proof that this config builds, see https://travis-ci.org/mkfifo/bone-lisp/builds/144694857

I am building this for linux under both clang and gcc, it failed under osx (see https://travis-ci.org/mkfifo/bone-lisp/builds/144694305) so I have not included osx in this submitted config.

### CODE REVIEW

**Comment by wolfgangj** [comment]
Thank you, I will do this.

The "gcc build" currently also compiles with clang since our Makefile does not yet take into account the `CC` environment variable. Do you know how to fix this? If not, I can do it, but it will take me a few days before I get to it. (Using autotools or even cmake does not count as a solution :))

Building on non-free systems is not very important for me, so it's fine to not include OS X (though it seems like it would not be very hard to fix the two problems). Is it possible to build on any BSDs?

By the way, `make test` will also build the executable first if it's not up to date yet, so we don't have to call `make` first. Since we do both now, it tries to build twice in the OS X build. But this is not very important since it shouldn't fail usually. ;)

**Comment by wolfgangj** [comment]
I have done as you told me, so this should hopefully work now. :)

**Comment by chrisosaurus** [comment]
Awesome, thanks, it is working.

Ahh I hadn't caught that.
I can update the Makefile to take CC into account, I'd rather avoid using cmake to be honest.

I will try look at this today.

As for other platforms: travis-ci only supports osx and linux.
I think it would be nice to support osx as a platform if possible, as it is posix. I don't use osx - just seems like low hanging fruit.

**Comment by wolfgangj** [comment]
Okay great - I would prefer to keep a simple Makefile.

If it compiles on OS X it will probably also work on BSDs, and it should be really easy. I will try to make the required changes.

**Comment by chrisosaurus** [comment]
heh, travis is now showing my PR builds successfully. Cute.

I have updated the Makefile to _not_ specify CC, this way it uses the system specified CC.

We can see for the gcc travis this is gcc https://travis-ci.org/mkfifo/bone-lisp/jobs/145198927
and for the clang travis this is clang https://travis-ci.org/mkfifo/bone-lisp/jobs/145198928

**Comment by wolfgangj** [comment]
Thanks, this works now. :)

**Pull request merged**
